/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author aaditya
 */

public class Manlogin extends javax.swing.JFrame {
    // managers analysis table
    // conatins the whole date_log table
    /**
     * Creates new form Manlogin
     */
    public Manlogin() {
        initComponents();
        getContentPane().setBackground(Color.GRAY);
    }
    private static final String USERNAME="root";
    private static final String PASSWORD="1234";
    private static final String CONN_STRING="jdbc:mysql://localhost:3306/time_analyzer?autoReconnect=true&useSSL=false";
    private double getval;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private String ReturnType(int type_id){
        switch(type_id){
            case 1: getval=0.9;return "Design";
            case 2: getval=0.75;return "Testing";
            case 3: getval=1.0;return "Coding";
            case 4: getval=0.8;return "Management";
            case 5: getval=1.2;return "Algorithms";
            case 6: getval=0.8;return "UI/UX";
            default: getval=0.0;return "Others";
        }
    }   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Date_log = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Top_emp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TypeBest = new javax.swing.JTable();
        AddProj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        End = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Start.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Start.setForeground(new java.awt.Color(102, 0, 102));
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Date_log.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Hours Worked", "Effective Hours"
            }
        ));
        jScrollPane1.setViewportView(Date_log);

        jLabel1.setFont(new java.awt.Font("PilGi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Most Working Employee");

        Top_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top_empActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("PilGi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Most Working Employee By Type");

        TypeBest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Name"
            }
        ));
        jScrollPane4.setViewportView(TypeBest);

        AddProj.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddProj.setForeground(new java.awt.Color(102, 0, 102));
        AddProj.setText("Add Project");
        AddProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProjActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("ProMan16");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel4.setText("TM");

        End.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        End.setForeground(new java.awt.Color(102, 0, 102));
        End.setText("Close");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Top_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(AddProj)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Start)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(End)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addComponent(Start)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Top_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddProj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(End)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String[][] date_log = new String[5000][2];
    public String[][] mod_date_log = new String[5000][4];
    
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        Connection conn = null;
        try{
            conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            Statement stmt =(Statement) conn.createStatement();
            String print_name;
            print_name = "select emp_id,sum(hours_worked) from date_log group by emp_id;";
            ResultSet rs = stmt.executeQuery(print_name);
            int i=0;
            while(rs.next()){
                date_log[i][0]=(rs.getString("emp_id"));
                date_log[i][1]=(rs.getString("sum(hours_worked)"));
                i++;
            }
            print_name = "Select emp_id,Name,sum(hours),type_id from Employee natural join date_log group by emp_id;";
            rs=stmt.executeQuery(print_name);
            i=0;
            while(rs.next()){
                mod_date_log[i][0] = rs.getString("emp_id");
                mod_date_log[i][1] = rs.getString("Name");
                mod_date_log[i][2] = rs.getString("sum(hours)");
                mod_date_log[i][3] = rs.getString("type_id");
                i++;
            }
            // find out the best of all
            DefaultTableModel model_2 = (DefaultTableModel) TypeBest.getModel();
            model_2.setNumRows(0);
            for(int j=1;j<=6;j++){
                int index;
                index = getBestType(Integer.toString(j),i);
                //System.out.println(mod_date_log[index][0]+mod_date_log[index][1]+mod_date_log[index][2]+mod_date_log[index][3]);
                Object[] row = {ReturnType(Integer.parseInt(mod_date_log[index][3])),mod_date_log[index][1]};
                
                model_2.addRow(row);
            }
                        //let it run first
            DefaultTableModel model_1 = (DefaultTableModel) Date_log.getModel();
            model_1.setNumRows(0);
            for(int j=0;j<i;j++){
                System.out.println(date_log[j][0]+date_log[j][1]);
                Object[] row = {date_log[j][0],date_log[j][1],(int)(Integer.parseInt(date_log[j][1])*getval)};
                
            
            model_1.addRow(row);
            }
            Top_emp.setText(getBestEmployee(i));
        }
            
        catch(SQLException e){
            System.out.println("Didnot happen"+e);
        }

    }//GEN-LAST:event_StartActionPerformed

    private int getBestType(String type_id,int len){
        int max=0;
        int in=0;
        for(int i=0;i<len;i++){
            if((mod_date_log[i][3]).equals(type_id))
                if(max<Integer.parseInt(mod_date_log[i][2])){
                    max=Integer.parseInt(mod_date_log[i][2]);
                    in=i;
                }
        }
        return in;
    }
    private String getBestEmployee(int len){
        int max=0;
        String id_picked=new String();
        for(int i=0;i<len;i++){
            if(Integer.parseInt(date_log[i][1])>max){
                max=Integer.parseInt(date_log[i][1]);
                id_picked=Integer.toString(i);
            }
        }
        return date_log[Integer.parseInt(id_picked)][0];
    }
    private void Top_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Top_empActionPerformed

    private void AddProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProjActionPerformed
        Recommend rc = new Recommend();
        rc.setLocationRelativeTo(null);
        rc.setVisible(true);
    }//GEN-LAST:event_AddProjActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProj;
    private javax.swing.JTable Date_log;
    private javax.swing.JButton End;
    private javax.swing.JButton Start;
    private javax.swing.JTextField Top_emp;
    private javax.swing.JTable TypeBest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
