/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author aaditya
 */
public class Recommend extends javax.swing.JFrame {

    /**
     * Creates new form Recommend
     */
    public Recommend() {
        initComponents();
        getContentPane().setBackground(Color.GRAY);
    }
    private static final String USERNAME="root";
    private static final String PASSWORD="1234";
    private static final String CONN_STRING="jdbc:mysql://localhost:3306/time_analyzer?autoReconnect=true&useSSL=false";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Exp = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Desp = new javax.swing.JComboBox();
        Testp = new javax.swing.JComboBox();
        Codp = new javax.swing.JComboBox();
        Manp = new javax.swing.JComboBox();
        Alp = new javax.swing.JComboBox();
        up = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Numpep = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecomendTabel = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Experience Need");

        Exp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Exp.setForeground(new java.awt.Color(102, 0, 102));
        Exp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes ", "No", " " }));
        Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("PilGi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Type Information");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Design");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Testing");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Coding");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Management");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Algorithms");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("UI/UX");

        Desp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Desp.setForeground(new java.awt.Color(102, 0, 102));
        Desp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        Testp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Testp.setForeground(new java.awt.Color(102, 0, 102));
        Testp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        Codp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Codp.setForeground(new java.awt.Color(102, 0, 102));
        Codp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        Manp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Manp.setForeground(new java.awt.Color(102, 0, 102));
        Manp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        Alp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Alp.setForeground(new java.awt.Color(102, 0, 102));
        Alp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        up.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        up.setForeground(new java.awt.Color(102, 0, 102));
        up.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Highly", "Yes", "No" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setText("Number Of People");

        Start.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Start.setForeground(new java.awt.Color(102, 0, 102));
        Start.setText("Recommend");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        RecomendTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Recommendations"
            }
        ));
        jScrollPane2.setViewportView(RecomendTabel);

        jLabel10.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("ProMan16");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel11.setText("TM");

        jLabel12.setFont(new java.awt.Font("PilGi", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 153));
        jLabel12.setText("Select the best people for your project");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Start)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Desp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Testp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Codp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Alp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(up, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numpep))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Desp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Testp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Codp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Manp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Alp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Numpep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private float [][] feature_matrix = new float [1000][8];
    private float [] new_matrix = new float [8];
    private float[][] distance_matrix = new float[1000][2];
    private int putvalue(String s){
        switch (s){
            case "Highly": return 5;
            case "Yes": return 1;
            case "No": return 0;
        }
        return 0;
    }
    private void normalize(int len){
        float [] avg = new float[len];
        for(int i=2;i<8;i++){
            int n=0;
            avg[i]=0;
            for(int j=0;j<len;j++){
                avg[i]+=this.feature_matrix[j][i];
                if(this.feature_matrix[j][i]!=0)
                    {n+=1;}
            }
            avg[i]/=n;
            //System.out.print(avg[i]+"  ");
        }
        for(int i=0;i<len;i++){
            for(int j=2;j<8;j++){
                this.feature_matrix[i][j]/=avg[j];
            }
        }
    }
    private void dist_calc(int len){
        // take values from swing
        new_matrix[1]=(putvalue(Exp.getSelectedItem().toString()))/2;  // weightage to this is less
        new_matrix[2]=putvalue(Desp.getSelectedItem().toString());
        new_matrix[3]=putvalue(Testp.getSelectedItem().toString());
        new_matrix[4]=putvalue(Codp.getSelectedItem().toString());
        new_matrix[5]=putvalue(Manp.getSelectedItem().toString());
        new_matrix[6]=putvalue(Alp.getSelectedItem().toString());
        new_matrix[7]=putvalue(up.getSelectedItem().toString());
        System.out.println("*******************************");
        for(int i=0;i<7;i++)
            System.out.print(new_matrix[i]+" ");
        System.out.println();
        for(int i=0;i<len;i++){
            distance_matrix[i][0]=feature_matrix[i][0];
            System.out.println(feature_matrix[i][0]);
            distance_matrix[i][1]=0;
            for(int j=1;j<8;j++){
                distance_matrix[i][1]+=((feature_matrix[i][j]-new_matrix[j])*(feature_matrix[i][j]-new_matrix[j]));
            }
            System.out.println(distance_matrix[i][0]+"  "+distance_matrix[i][1]+"  ");
        }
    }
    private void knn(int len){
        dist_calc(len);
        int k = Integer.parseInt(Numpep.getText());
        // find the k least distances from distance matrix
        // find 1 first
        // sort to get k smallest distances
        float [] res_arr = new float[k];
        for(int j=0;j<k;j++){
            float dist=Float.MAX_VALUE;
            int index=0;
            for(int i=0;i<len;i++){
                if(distance_matrix[i][1]<dist){
                    index=i;
                    dist=(distance_matrix[i][1]);
                }
            } 
            res_arr[j]=feature_matrix[index][0];
            distance_matrix[index][1]=Float.MAX_VALUE;
        }
        //System.out.println(feature_matrix[index][0]);
        /*java.util.Arrays.sort(distance_matrix, new java.util.Comparator<float[]>() {
        public int compare(float[] a, float[] b) {
            return Float.compare(a[0], b[0]);
            }
        });*/
        System.out.println("**********************************");
        for (int i=0;i<k;i++){
            System.out.print(" "+res_arr[i]);
        }
        for(int j=0;j<k;j++){
                Object[] row = {res_arr[j]};
                DefaultTableModel model = (DefaultTableModel) RecomendTabel.getModel();
                model.addRow(row);
            }
    } 
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        if(Numpep.getText().equals("0")||Numpep.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Input the proper amount of people");
        Connection conn = null;
        try{
            conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            Statement stmt =(Statement) conn.createStatement();
            String print_name;
            int i=0;
            print_name = "select emp_id,sum(hours_worked) as tot_hours,Experience,type_id from date_log natural join Employee group by emp_id;";
            ResultSet rs = stmt.executeQuery(print_name);
            while(rs.next()){
                feature_matrix[i][0]=Float.parseFloat(rs.getString("emp_id"));
                feature_matrix[i][1]=Float.parseFloat(rs.getString("Experience"));
                int id=Integer.parseInt(rs.getString("type_id"));
                for(int x=2;x<8;x++){
                    if(x==(id+1)){
                        feature_matrix[i][x]=Float.parseFloat(rs.getString("tot_hours"));
                        }
                    else feature_matrix[i][x]=0;
                    }
                i++;
                }
            //lets normalize
            normalize(i);
            /*for(int j=0;j<i;j++){
                for(int x=0;x<8;x++){
                    System.out.print(feature_matrix[j][x]+"  ");
                    }
                System.out.println();
                }*/
           // System.out.println(putvalue(Exp.getSelectedItem().toString()));
           // lets calculate distance now
            knn(i);
            }
        catch(SQLException e){
            System.out.println("Didnot happen"+e);
        }
    }//GEN-LAST:event_StartActionPerformed

    private void ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recommend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recommend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recommend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recommend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recommend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Alp;
    private javax.swing.JComboBox Codp;
    private javax.swing.JComboBox Desp;
    private javax.swing.JComboBox Exp;
    private javax.swing.JComboBox Manp;
    private javax.swing.JTextField Numpep;
    private javax.swing.JTable RecomendTabel;
    private javax.swing.JButton Start;
    private javax.swing.JComboBox Testp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox up;
    // End of variables declaration//GEN-END:variables
}
